/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountReceivableIncome } from './accountReceivableIncome';

export class AccountReceivableResponse {
    /**
    * Ledger ID.
    */
    'ledgerId': string;
    /**
    * Organization ID.
    */
    'orgId': string;
    /**
    * Site ID.
    */
    'siteId': string;
    /**
    * Location ID.
    */
    'locationId': string;
    /**
    * Opening balance.
    */
    'openingBalance': number;
    /**
    * Closing balance.
    */
    'closingBalance': number;
    /**
    * Check asset amount.
    */
    'payments': number;
    /**
    * Income details.
    */
    'income': Array<AccountReceivableIncome>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "openingBalance",
            "baseName": "openingBalance",
            "type": "number"
        },
        {
            "name": "closingBalance",
            "baseName": "closingBalance",
            "type": "number"
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "number"
        },
        {
            "name": "income",
            "baseName": "income",
            "type": "Array<AccountReceivableIncome>"
        }    ];

    static getAttributeTypeMap() {
        return AccountReceivableResponse.attributeTypeMap;
    }
}

