/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountReceivableType } from './accountReceivableType';

export class AccountReceivableRuleResponse {
    /**
    * Account Receivable Rule ID
    */
    'accountReceivableRuleId': string;
    /**
    * General Ledger Account ID
    */
    'generalLedgerAccountId': string;
    'accountReceivableType': AccountReceivableType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountReceivableRuleId",
            "baseName": "accountReceivableRuleId",
            "type": "string"
        },
        {
            "name": "generalLedgerAccountId",
            "baseName": "generalLedgerAccountId",
            "type": "string"
        },
        {
            "name": "accountReceivableType",
            "baseName": "accountReceivableType",
            "type": "AccountReceivableType"
        }    ];

    static getAttributeTypeMap() {
        return AccountReceivableRuleResponse.attributeTypeMap;
    }
}

export namespace AccountReceivableRuleResponse {
}
