/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountReceivableResponse {
    /**
    * Ledger ID.
    */
    'ledgerId': string;
    /**
    * Organization ID.
    */
    'orgId': string;
    /**
    * Site ID.
    */
    'siteId': string;
    /**
    * Location ID.
    */
    'locationId': string;
    /**
    * Opening balance.
    */
    'openingBalance': number;
    /**
    * Closing balance.
    */
    'closingBalance': number;
    /**
    * Fee income.
    */
    'feeIncome': number;
    /**
    * Merchandise income.
    */
    'merchandiseIncome': number;
    /**
    * Rental income.
    */
    'rentalIncome': number;
    /**
    * Other income.
    */
    'otherIncome': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "openingBalance",
            "baseName": "openingBalance",
            "type": "number"
        },
        {
            "name": "closingBalance",
            "baseName": "closingBalance",
            "type": "number"
        },
        {
            "name": "feeIncome",
            "baseName": "feeIncome",
            "type": "number"
        },
        {
            "name": "merchandiseIncome",
            "baseName": "merchandiseIncome",
            "type": "number"
        },
        {
            "name": "rentalIncome",
            "baseName": "rentalIncome",
            "type": "number"
        },
        {
            "name": "otherIncome",
            "baseName": "otherIncome",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AccountReceivableResponse.attributeTypeMap;
    }
}

