/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum CheckAssetType {
    AchDebit = <any> 'ach_debit',
    AfterpayClearpay = <any> 'afterpay_clearpay',
    Alipay = <any> 'alipay',
    AmexCredit = <any> 'amex_credit',
    AmexDebit = <any> 'amex_debit',
    ApplePay = <any> 'apple_pay',
    BacsDebit = <any> 'bacs_debit',
    Bancontact = <any> 'bancontact',
    BankTransfer = <any> 'bank_transfer',
    Cash = <any> 'cash',
    Check = <any> 'check',
    DinersCard = <any> 'diners_card',
    DiscoverCredit = <any> 'discover_credit',
    DiscoverDebit = <any> 'discover_debit',
    Eps = <any> 'eps',
    Giropay = <any> 'giropay',
    GooglePay = <any> 'google_pay',
    Ideal = <any> 'ideal',
    Klarna = <any> 'klarna',
    MastercardCredit = <any> 'mastercard_credit',
    MastercardDebit = <any> 'mastercard_debit',
    Multibanco = <any> 'multibanco',
    Oxxo = <any> 'oxxo',
    Other = <any> 'other',
    P24 = <any> 'p24',
    Paypal = <any> 'paypal',
    SepaDebit = <any> 'sepa_debit',
    Sofort = <any> 'sofort',
    VisaCredit = <any> 'visa_credit',
    VisaDebit = <any> 'visa_debit',
    WechatPay = <any> 'wechat_pay'
}
