/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckAssetType } from './checkAssetType';

export class CheckAssetRuleResponse {
    /**
    * Check Asset Rule ID
    */
    'checkAssetRuleId': string;
    /**
    * General Ledger Account ID
    */
    'generalLedgerAccountId': string;
    'checkAssetType': CheckAssetType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checkAssetRuleId",
            "baseName": "checkAssetRuleId",
            "type": "string"
        },
        {
            "name": "generalLedgerAccountId",
            "baseName": "generalLedgerAccountId",
            "type": "string"
        },
        {
            "name": "checkAssetType",
            "baseName": "checkAssetType",
            "type": "CheckAssetType"
        }    ];

    static getAttributeTypeMap() {
        return CheckAssetRuleResponse.attributeTypeMap;
    }
}

export namespace CheckAssetRuleResponse {
}
