/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FeeIncomeType } from './feeIncomeType';

export class CreateFeeIncomeRuleRequest {
    /**
    * General Ledger Account ID
    */
    'generalLedgerAccountId': string;
    'feeIncomeType': FeeIncomeType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generalLedgerAccountId",
            "baseName": "generalLedgerAccountId",
            "type": "string"
        },
        {
            "name": "feeIncomeType",
            "baseName": "feeIncomeType",
            "type": "FeeIncomeType"
        }    ];

    static getAttributeTypeMap() {
        return CreateFeeIncomeRuleRequest.attributeTypeMap;
    }
}

export namespace CreateFeeIncomeRuleRequest {
}
