/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeneralLedgerAccountType } from './generalLedgerAccountType';

export class CreateGeneralLedgerAccountRequest {
    /**
    * Title of the account
    */
    'title': string;
    /**
    * Description of the account
    */
    'description'?: string;
    /**
    * Alias for the account
    */
    'alias'?: string;
    'generalLedgerAccountType': GeneralLedgerAccountType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string"
        },
        {
            "name": "generalLedgerAccountType",
            "baseName": "generalLedgerAccountType",
            "type": "GeneralLedgerAccountType"
        }    ];

    static getAttributeTypeMap() {
        return CreateGeneralLedgerAccountRequest.attributeTypeMap;
    }
}

export namespace CreateGeneralLedgerAccountRequest {
}
