/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum FeeIncomeType {
    AdministrativeFee = <any> 'administrative_fee',
    ElectricityFee = <any> 'electricity_fee',
    InventoryFee = <any> 'inventory_fee',
    LateFee = <any> 'late_fee',
    LienFee = <any> 'lien_fee',
    NsfFee = <any> 'nsf_fee',
    StatementFee = <any> 'statement_fee',
    UnknownFee = <any> 'unknown_fee'
}
