/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeneralLedgerAccountType } from './generalLedgerAccountType';

export class GeneralLedgerAccountResponse {
    /**
    * General Ledger Account ID.
    */
    'generalLedgerAccountId': string;
    'generalLedgerAccountType': GeneralLedgerAccountType;
    /**
    * General Ledger Account Title
    */
    'title': string;
    /**
    * General Ledger Account Description
    */
    'description': string | null;
    /**
    * Alias for the Account
    */
    'alias': string | null;
    /**
    * Organization ID.
    */
    'orgId': string;
    /**
    * Site ID.
    */
    'siteId': string;
    /**
    * Credits.
    */
    'credits': number;
    /**
    * Debits.
    */
    'debits': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generalLedgerAccountId",
            "baseName": "generalLedgerAccountId",
            "type": "string"
        },
        {
            "name": "generalLedgerAccountType",
            "baseName": "generalLedgerAccountType",
            "type": "GeneralLedgerAccountType"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "credits",
            "baseName": "credits",
            "type": "number"
        },
        {
            "name": "debits",
            "baseName": "debits",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GeneralLedgerAccountResponse.attributeTypeMap;
    }
}

export namespace GeneralLedgerAccountResponse {
}
