/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeneralLedgerEntryType } from './generalLedgerEntryType';

export class GeneralLedgerEntryResponse {
    /**
    * ID of the General Entry Ledger
    */
    'generalLedgerEntryId': string;
    /**
    * ID of the Ledger
    */
    'ledgerId': string;
    /**
    * ID of the Org
    */
    'orgId': string;
    /**
    * ID of the Site
    */
    'siteId': string;
    /**
    * ID of the Location
    */
    'locationId': string;
    /**
    * description of the entry
    */
    'description'?: string;
    /**
    * tag of the entry
    */
    'tag': string;
    'generalLedgerEntryType': GeneralLedgerEntryType;
    /**
    * The date the change was made.
    */
    'entryDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generalLedgerEntryId",
            "baseName": "generalLedgerEntryId",
            "type": "string"
        },
        {
            "name": "ledgerId",
            "baseName": "ledgerId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string"
        },
        {
            "name": "generalLedgerEntryType",
            "baseName": "generalLedgerEntryType",
            "type": "GeneralLedgerEntryType"
        },
        {
            "name": "entryDate",
            "baseName": "entryDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GeneralLedgerEntryResponse.attributeTypeMap;
    }
}

export namespace GeneralLedgerEntryResponse {
}
