/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GeneralLedgerAccountLineItemResponse {
    /**
    * Credit amount
    */
    'creditAmount': number;
    /**
    * Debit amount
    */
    'debitAmount': number;
    /**
    * Description
    */
    'description': string | null;
    /**
    * The date the entry was made.
    */
    'entryDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creditAmount",
            "baseName": "creditAmount",
            "type": "number"
        },
        {
            "name": "debitAmount",
            "baseName": "debitAmount",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entryDate",
            "baseName": "entryDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return GeneralLedgerAccountLineItemResponse.attributeTypeMap;
    }
}

