/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum GeneralLedgerAccountType {
    Asset = <any> 'asset',
    Liability = <any> 'liability',
    Equity = <any> 'equity',
    Revenue = <any> 'revenue',
    Expense = <any> 'expense'
}
