/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeneralLedgerAccountType } from './generalLedgerAccountType';

export class GeneralLedgerAccountResponse {
    /**
    * General Ledger Account ID.
    */
    'generalLedgerAccountId': string;
    'type': GeneralLedgerAccountType;
    /**
    * General Ledger Account Title
    */
    'title': string;
    /**
    * General Ledger Account Description
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generalLedgerAccountId",
            "baseName": "generalLedgerAccountId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GeneralLedgerAccountType"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GeneralLedgerAccountResponse.attributeTypeMap;
    }
}

export namespace GeneralLedgerAccountResponse {
}
