/**
 * ManageSpace Accounting API
 * ManageSpace Accounting API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum MerchandiseIncomeType {
    Boxes = <any> 'boxes',
    Locks = <any> 'locks',
    Equipment = <any> 'equipment',
    Services = <any> 'services',
    TruckRental = <any> 'truck_rental',
    Other = <any> 'other'
}
